apiVersion: v1
kind: Service
metadata:
  name: httpserver-service-b
  namespace: httpserver-service-b
spec:
  selector:
    app: httpserver-b
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 3000