apiVersion: apps/v1
kind: Deployment
metadata:
  name: httpserver-app
  namespace: default
spec:
  replicas: 3
  selector:
    matchLabels:
      app: httpserver
  template:
    metadata:
      labels:
        app: httpserver
    spec:
      containers:
        - name: httpserver
          image: dcbarringer/myhttpserver:0.2.0
          ports:
            - name: tcp
              containerPort: 3000