apiVersion: v1
kind: Service
metadata:
  name: httpserver-service
  namespace: default
spec:
  selector:
    app: httpserver
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 3000